"""
physics/tpa_fcd.py
==================
Two-Photon Absorption (TPA) and Free-Carrier Dispersion (FCD) models
for Silicon Microring Resonators.

Physical Background
-------------------
TPA is a third-order nonlinear optical process in which two photons are
simultaneously absorbed to excite a single electron-hole pair across the
silicon bandgap (E_g ≈ 1.12 eV at 300 K). At λ = 1550 nm the single-photon
energy (ħω ≈ 0.8 eV) is sub-bandgap, so single-photon absorption is negligible.
However, two photons together provide ≈1.6 eV — above the bandgap.

TPA rate (intensity form):
    dI/dz = -β_TPA · I²

In the CMT (Coupled-Mode Theory) ring model with intracavity field amplitude a(t)
normalized so that |a|² = intracavity photon number N_phot:

    G_TPA = β_eff · |a|⁴     [free carriers/s generated by TPA]

The generated free carriers (density N_c) undergo:
1. **Free-Carrier Absorption (FCA)**: additional linear loss ∝ N_c.
2. **Free-Carrier Dispersion (FCD)**: refractive index change → resonance shift.
3. **Thermal effects**: heating via FCA → thermo-optic shift (handled in thermo_optic.py).

Free-carrier density ODE:
    dN_c/dt = G_TPA - N_c / τ_FC

FCD resonance shift (Soref–Bennett model):
    δω_FC = (ω₀ / n₀) · Δn_FC(N_c)
           = (ω₀ / n₀) · dn_FC · N_c

All functions in this module operate on NumPy arrays and are designed for
vectorized computation over N_nodes simultaneously (no Python loops).

References
----------
[1] Borghi et al., "Nonlinear silicon photonics." J. Opt. 19, 093004 (2017).
[2] Soref & Bennett, IEEE J. Quantum Electron. 23, 123–129 (1987).
[3] Dinu et al., Appl. Phys. Lett. 82, 2954 (2003). [TPA coefficient measurement]
"""

from __future__ import annotations
import numpy as np
from numpy.typing import NDArray
from typing import Union

from physics.constants import (
    SiliconConstants,
    DerivedOpticalConstants,
    OMEGA_0,
    HBAR,
    C_LIGHT,
    SI,
    DERIVED,
)

# Type alias for batched float arrays
FloatArray = NDArray[np.float64]


# ─────────────────────────────────────────────────────────────────────────────
# TPA carrier generation
# ─────────────────────────────────────────────────────────────────────────────

def tpa_generation_rate(
    a_sq: FloatArray,
    dc: DerivedOpticalConstants = DERIVED,
) -> FloatArray:
    """
    Compute the TPA-driven free-carrier generation rate G_TPA [m⁻³/s].

    In CMT photon-number normalisation (|a|² = N_phot, intracavity photons):

        G_TPA = β_eff · |a|⁴

    where:
        β_eff = β_TPA · c² / (2 · ħω₀ · n_g² · V_eff)   [m⁻³ s⁻¹ / photon²]

    This is a strictly quadratic function of optical intensity, which is the
    hallmark nonlinearity that drives all downstream effects (FCD, thermo-optic).

    Parameters
    ----------
    a_sq : NDArray[float64]  shape [..., N_nodes]
        Intracavity photon number |a(t)|² per MRR node.
        Units: dimensionless (normalized photon number) or physical photons.
    dc : DerivedOpticalConstants
        Pre-computed derived constants (cached for performance).

    Returns
    -------
    NDArray[float64]  shape [..., N_nodes]
        TPA carrier generation rate G_TPA [m⁻³/s].

    Notes
    -----
    The |a|⁴ term arises because:
        I ∝ |a|²   →   I² ∝ |a|⁴
    For numerical stability, a_sq is clipped to avoid overflow in a_sq².
    """
    # Clip to prevent float64 overflow in squaring (~1e154 is safe)
    a_sq_clipped = np.clip(a_sq, 0.0, 1e38)
    return dc.beta_eff * (a_sq_clipped ** 2)


def tpa_intensity_loss(
    intensity: FloatArray,
    mat: SiliconConstants = SI,
) -> FloatArray:
    """
    Compute the TPA power loss rate per unit propagation length [W/m].

        dI/dz|_TPA = -β_TPA · I²

    Parameters
    ----------
    intensity : NDArray[float64]  shape [...]
        Optical intensity [W/m²].
    mat : SiliconConstants
        Material constants.

    Returns
    -------
    NDArray[float64]
        Loss rate -β_TPA · I²  [W/m³].

    Notes
    -----
    This is the waveguide propagation form of TPA, useful for verifying
    against the ring cavity CMT form used in `tpa_generation_rate`.
    """
    return -mat.beta_TPA * (intensity ** 2)


# ─────────────────────────────────────────────────────────────────────────────
# Free-Carrier Absorption (FCA)
# ─────────────────────────────────────────────────────────────────────────────

def fca_loss_rate(
    N_c: FloatArray,
    a_sq: FloatArray,
    mat: SiliconConstants = SI,
    dc: DerivedOpticalConstants = DERIVED,
) -> FloatArray:
    """
    Compute the FCA-induced field decay rate contribution [rad/s].

    Free carriers generated by TPA absorb photons with cross-section σ_FCA:

        Δα_FCA = σ_FCA · N_c   [1/m, field loss coefficient]

    In CMT terms, this adds an extra loss to the field decay rate:
        κ_FCA = σ_FCA · v_g · N_c   [rad/s]

    The total effective field decay rate becomes:
        κ_eff = 0.5 · κ_total + κ_FCA / 2

    Parameters
    ----------
    N_c : NDArray[float64]  shape [..., N_nodes]
        Free-carrier density [m⁻³].
    a_sq : NDArray[float64]  shape [..., N_nodes]
        Intracavity photon number |a|² (not used directly but kept for API
        consistency with the heat generation term).
    mat : SiliconConstants
        Silicon material constants.
    dc : DerivedOpticalConstants
        Derived constants (provides v_g implicitly via kappa_i relationship).

    Returns
    -------
    NDArray[float64]  shape [..., N_nodes]
        FCA contribution to field decay rate κ_FCA [rad/s].
    """
    v_g = C_LIGHT / mat.n_group
    return mat.sigma_FCA * v_g * np.clip(N_c, 0.0, None)


# ─────────────────────────────────────────────────────────────────────────────
# Free-Carrier Density ODE
# ─────────────────────────────────────────────────────────────────────────────

def free_carrier_ode(
    N_c: FloatArray,
    a_sq: FloatArray,
    dc: DerivedOpticalConstants = DERIVED,
    mat: SiliconConstants = SI,
) -> FloatArray:
    """
    Evaluate the right-hand side of the free-carrier density ODE.

    Full rate equation for free-carrier density N_c [m⁻³]:

        dN_c/dt = G_TPA(|a|²) - N_c / τ_FC

    where:
        G_TPA = β_eff · |a|⁴          [TPA generation]
        N_c / τ_FC                     [free-carrier recombination/diffusion]

    This ODE is stiff when τ_FC >> T_rt (ring round-trip time), making
    Euler integration adequate only if dt << τ_FC. For larger dt, use
    the analytical steady-state approximation or RK4 (see mrr_dynamics.py).

    Parameters
    ----------
    N_c : NDArray[float64]  shape [..., N_nodes]
        Current free-carrier density [m⁻³].
    a_sq : NDArray[float64]  shape [..., N_nodes]
        Current intracavity photon number |a(t)|².
    dc : DerivedOpticalConstants
        Pre-computed derived constants.
    mat : SiliconConstants
        Silicon material constants.

    Returns
    -------
    NDArray[float64]  shape [..., N_nodes]
        dN_c/dt  [m⁻³/s].

    Examples
    --------
    >>> import numpy as np
    >>> from physics.tpa_fcd import free_carrier_ode
    >>> N_c = np.zeros(64)
    >>> a_sq = np.ones(64) * 1e6   # 10^6 photons
    >>> dNc_dt = free_carrier_ode(N_c, a_sq)
    >>> dNc_dt.shape
    (64,)
    """
    G_tpa   = tpa_generation_rate(a_sq, dc)
    decay   = np.clip(N_c, 0.0, None) / mat.tau_FC
    return G_tpa - decay


def free_carrier_steady_state(
    a_sq: FloatArray,
    dc: DerivedOpticalConstants = DERIVED,
    mat: SiliconConstants = SI,
) -> FloatArray:
    """
    Compute the steady-state free-carrier density N_c^{ss} [m⁻³].

    At steady state (dN_c/dt = 0):

        N_c^{ss} = G_TPA · τ_FC = β_eff · τ_FC · |a|⁴

    This is the analytical equilibrium solution, useful for:
    - Initialising the ODE solver near equilibrium.
    - Fast approximation when τ_FC < simulation timestep.

    Parameters
    ----------
    a_sq : NDArray[float64]  shape [..., N_nodes]
        Intracavity photon number |a|².
    dc : DerivedOpticalConstants
        Derived constants.
    mat : SiliconConstants
        Material constants.

    Returns
    -------
    NDArray[float64]  shape [..., N_nodes]
        Steady-state free-carrier density [m⁻³].
    """
    return tpa_generation_rate(a_sq, dc) * mat.tau_FC


# ─────────────────────────────────────────────────────────────────────────────
# Free-Carrier Dispersion (FCD) — resonance shift
# ─────────────────────────────────────────────────────────────────────────────

def fcd_resonance_shift(
    N_c: FloatArray,
    dc: DerivedOpticalConstants = DERIVED,
) -> FloatArray:
    """
    Compute the FCD-induced resonance frequency shift δω_FC [rad/s].

    From the Soref–Bennett model for free carriers in silicon:

        Δn_FCD = dn_FC · N_c        (N_c in m⁻³, dn_FC < 0 for electrons)

    Resonance shift:
        δω_FC = (ω₀ / n₀) · Δn_FCD = (ω₀ / n₀) · dn_FC · N_c

    Since dn_FC = -1.73×10⁻²⁷ m³ < 0:
        δω_FC < 0   →   resonance BLUE-SHIFTS with increasing carrier density.

    This opposes the thermo-optic RED-shift (dn/dT > 0), creating a
    complex nonlinear interplay that enriches reservoir dynamics.

    Parameters
    ----------
    N_c : NDArray[float64]  shape [..., N_nodes]
        Free-carrier density [m⁻³].
    dc : DerivedOpticalConstants
        Pre-computed derived constants (contains dw_FC_coef).

    Returns
    -------
    NDArray[float64]  shape [..., N_nodes]
        Resonance detuning from FCD [rad/s].
        Negative values indicate blue-shift (resonance moves away from pump).

    Notes
    -----
    The sign convention here matches the CMT detuning Δω:
        Δω = ω_pump - ω_res(t) - δω_FC(t) - δω_TO(t)
    A negative δω_FC increases effective detuning, reducing intracavity buildup.
    """
    return dc.dw_FC_coef * np.clip(N_c, 0.0, None)


def fcd_refractive_index_change(
    N_c: FloatArray,
    mat: SiliconConstants = SI,
) -> FloatArray:
    """
    Compute refractive index change from free carriers Δn_FCD.

    Soref–Bennett model:
        Δn_FCD = dn_FC · N_c    (dn_FC = -1.73×10⁻²⁷ m³)

    For a carrier density N_c = 10²⁴ m⁻³ (typical during TPA):
        Δn_FCD ≈ -1.73×10⁻³   (about -0.05% of n₀)

    Parameters
    ----------
    N_c : NDArray[float64]  shape [..., N_nodes]
        Free-carrier density [m⁻³].
    mat : SiliconConstants
        Silicon material constants.

    Returns
    -------
    NDArray[float64]  shape [..., N_nodes]
        Refractive index change Δn_FCD (dimensionless, negative).
    """
    return mat.dn_FC * np.clip(N_c, 0.0, None)


# ─────────────────────────────────────────────────────────────────────────────
# Lorentzian cavity transfer function
# ─────────────────────────────────────────────────────────────────────────────

def lorentzian_transmission(
    delta_omega: FloatArray,
    kappa_total: float,
) -> FloatArray:
    """
    Compute the Lorentzian cavity intensity transfer function.

    For a driven ring resonator, the steady-state intracavity intensity
    follows a Lorentzian in the detuning Δω = ω_pump - ω_res:

        T_Lor(Δω) = (κ_total / 2)² / [(Δω)² + (κ_total / 2)²]

    This equals 1 at resonance (Δω = 0) and falls to 0.5 at Δω = κ_total/2
    (i.e., the half-bandwidth is κ_total/2 rad/s).

    In the ODE solver this represents the attenuation of the drive term:
        s_eff = s_in · T_Lor(Δω_total)

    Parameters
    ----------
    delta_omega : NDArray[float64]  shape [..., N_nodes]
        Total resonance detuning [rad/s]:
            Δω_total = Δω_0 + δω_FC + δω_TO
        where Δω_0 is the static cold-cavity detuning of the WDM channel.
    kappa_total : float
        Total field decay rate κ = κ_e + κ_i [rad/s].

    Returns
    -------
    NDArray[float64]  shape [..., N_nodes]
        Lorentzian transmission factor in [0, 1].

    Notes
    -----
    The factor of 2 in (κ/2)² comes from the CMT field equation convention
    where da/dt = -(κ/2)·a + drive, so the FWHM linewidth is κ (not κ/2).
    """
    half_kappa = 0.5 * kappa_total
    return (half_kappa ** 2) / (delta_omega ** 2 + half_kappa ** 2)


def lorentzian_complex_amplitude(
    delta_omega: FloatArray,
    kappa_e: float,
    kappa_total: float,
) -> NDArray[np.complex128]:
    """
    Compute the complex cavity amplitude transfer function (CMT steady state).

    In steady-state CMT, the intracavity field amplitude is:

        a_ss = sqrt(κ_e) · s_in / (κ_total/2 + j·Δω)

    This gives a complex Lorentzian with:
        |a_ss|² = κ_e · |s_in|² / [(Δω)² + (κ_total/2)²]

    Parameters
    ----------
    delta_omega : NDArray[float64]  shape [...]
        Detuning [rad/s].
    kappa_e : float
        External coupling rate [rad/s].
    kappa_total : float
        Total decay rate [rad/s].

    Returns
    -------
    NDArray[complex128]  shape [...]
        Complex transfer function H(Δω) = sqrt(κ_e) / (κ_total/2 + j·Δω).
    """
    denominator = 0.5 * kappa_total + 1j * delta_omega
    return np.sqrt(kappa_e) / denominator


# ─────────────────────────────────────────────────────────────────────────────
# Vectorized batch utilities
# ─────────────────────────────────────────────────────────────────────────────

def compute_tpa_fcd_derivatives(
    N_c: FloatArray,
    a_sq: FloatArray,
    dc: DerivedOpticalConstants = DERIVED,
    mat: SiliconConstants = SI,
) -> tuple[FloatArray, FloatArray, FloatArray]:
    """
    Compute all TPA/FCD-related quantities in a single vectorized pass.

    This is the performance-critical function called in the ODE inner loop.
    It computes, in one sweep over memory:
        1. dN_c/dt   — free-carrier ODE right-hand side
        2. δω_FC     — FCD resonance shift
        3. κ_FCA     — FCA extra loss contribution

    All operations are element-wise NumPy broadcasting with no Python loops.

    Parameters
    ----------
    N_c : NDArray[float64]  shape [..., N_nodes]
        Free-carrier density [m⁻³].
    a_sq : NDArray[float64]  shape [..., N_nodes]
        Intracavity photon number |a|².
    dc : DerivedOpticalConstants
    mat : SiliconConstants

    Returns
    -------
    dNc_dt : NDArray[float64]  shape [..., N_nodes]
        Free-carrier time derivative [m⁻³/s].
    delta_omega_FC : NDArray[float64]  shape [..., N_nodes]
        FCD resonance shift [rad/s].
    kappa_FCA : NDArray[float64]  shape [..., N_nodes]
        FCA decay rate contribution [rad/s].

    Performance
    -----------
    On a 64-node mesh with batch_size=2048 (shape [2048, 64]):
        - Single pass: ~0.3 ms on Intel Core i7 with MKL NumPy.
        - Memory: 3 × 2048 × 64 × 8 bytes ≈ 3 MB intermediate arrays.
    """
    # Clip inputs to physical range
    N_c_pos  = np.maximum(N_c,  0.0)
    a_sq_pos = np.maximum(a_sq, 0.0)

    # TPA generation: G = β_eff · |a|⁴
    a_sq_clipped = np.minimum(a_sq_pos, 1e38)
    G_tpa = dc.beta_eff * (a_sq_clipped ** 2)

    # Free-carrier ODE: dN_c/dt = G_TPA - N_c / τ_FC
    dNc_dt = G_tpa - N_c_pos / mat.tau_FC

    # FCD resonance shift: δω_FC = dw_FC_coef · N_c
    delta_omega_FC = dc.dw_FC_coef * N_c_pos

    # FCA extra loss: κ_FCA = σ_FCA · v_g · N_c
    v_g = C_LIGHT / mat.n_group
    kappa_FCA = mat.sigma_FCA * v_g * N_c_pos

    return dNc_dt, delta_omega_FC, kappa_FCA
